services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./config:/var/www/html/catcontrol/config
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/catcontrol

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_DATABASE=catcontrol
      - MYSQL_USER=phpuser
      - MYSQL_PASSWORD=meinpasswort
      - MYSQL_ROOT_PASSWORD=rootpasswort
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
